name: setup

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"
        cache: npm
        registry-url: 'https://registry.npmjs.org/'
