name: setup

inputs:
  node-version:
    description: "Node.js version to use"
    required: false
    default: "24.x"

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        registry-url: 'https://registry.npmjs.org/'

    - name: Install packages
      run: npm install
      shell: bash
