name: setup

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: "22.10.x"
        cache: npm
        registry-url: 'https://registry.npmjs.org/'

    - name: Install packages
      run: npm install
      shell: bash
