name: setup

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: "20.x"
        cache: npm

    - name: Install packages
      run: npm install
      shell: bash
