export default {
  ignores: ["contracts/mock/**/*.sol"],
  rules: {
    "compatible-pragma": "error",
    "curly": "off",
    "explicit-types": "error",
    "id-denylist": "error",
    "imports-on-top": "error",
    "max-state-vars": "error",
    "named-return-params": "off",
    "naming-convention": "off",
    "no-console": "error",
    "no-default-visibility": "error",
    "no-duplicate-imports": "error",
    "no-empty-blocks": "warn",
    "no-global-imports": "error",
    "no-restricted-syntax": "error",
    "no-send": "error",
    "no-tx-origin": "warn",
    "no-unchecked-calls": "error",
    "no-uninitialized-immutable-references": "error",
    "no-unused-vars": "error",
    "one-contract-per-file": "off",
    "private-vars": "off",
    "require-revert-reason": "error",
    "sort-imports": "off",
    "sort-members": "off",
    "sort-modifiers": "error",
  },
};
