name: "coverage"

on:
  workflow_run:
    workflows:
      - pre-release
    types:
      - completed
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run coverage
        env:
          NODE_OPTIONS: "--max_old_space_size=16384"
        run: npm run coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
