name: pre-release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  validate:
    name: Validate CHANGELOG
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'chore(release):') }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup

      - name: Validate structure
        run: npx tsx scripts/release/validate-changelog.cts
